export const state = {
  lang: localStorage.getItem('yoldash_lang') || 'fa',
  session: null,
  profile: null,
  businessProfile: null,
  loads: [],
  loadFilter: 'all',
  authMode: 'signin',
  selectedBusinessType: null,
  pendingSignupEmail: '',
  city: { origin: null, destination: null },
  fxData: null,
  fxTimer: null,
  chatTimer: null,
  notificationTimer: null,
  driverListings: [],
  driverFilter: 'all',
  driverScope: 'all',
  loadRealtimeChannel: null,
  loadRefreshTimer: null,
  loadRefreshDebounce: null,
  isSuperAdmin: false,
  adminUserMap: null,
  adminUserMapLayer: null,
  adminMapRows: [],
  adminMapRefreshTimer: null,
  adminMapHasInitialFit: false
};
